import React from "react";

const sizeClasses = {
  txtGilroySemiBold24: "font-gilroy font-semibold",
  txtGilroySemiBold20: "font-gilroy font-semibold",
  txtGilroyRegular14Black900: "font-gilroy font-normal",
  txtGilroyBold36: "font-bold font-gilroy",
  txtGilroyBold32: "font-bold font-gilroy",
  txtGilroyMedium18Red700: "font-gilroy font-medium",
  txtUrbanistItalicThin24: "font-hairline font-urbanist italic",
  txtGilroyMedium14Amber700: "font-gilroy font-medium",
  txtGilroySemiBold28: "font-gilroy font-semibold",
  txtGilroySemiBold18Red700: "font-gilroy font-semibold",
  txtGilroyMedium16BlueA700: "font-gilroy font-medium",
  txtGilroyRegular18: "font-gilroy font-normal",
  txtOpenSansMedium18: "font-medium font-opensans",
  txtOpenSansMedium14: "font-medium font-opensans",
  txtGilroySemiBold24Black900: "font-gilroy font-semibold",
  txtGilroySemiBold18Bluegray900: "font-gilroy font-semibold",
  txtOpenSansMedium16: "font-medium font-opensans",
  txtGilroyMedium12Bluegray400: "font-gilroy font-medium",
  txtGilroyMedium16Gray90002: "font-gilroy font-medium",
  txtGilroyMedium18Gray700: "font-gilroy font-medium",
  txtGilroyMedium18Black90002: "font-gilroy font-medium",
  txtGilroySemiBold28Bluegray900: "font-gilroy font-semibold",
  txtGilroyMedium14BlueA700: "font-gilroy font-medium",
  txtGilroyBold28: "font-bold font-gilroy",
  txtGilroySemiBold32: "font-gilroy font-semibold",
  txtGilroySemiBold18Green600: "font-gilroy font-semibold",
  txtGilroyMedium16Black90002: "font-gilroy font-medium",
  txtGilroyBold24: "font-bold font-gilroy",
  txtGilroyMedium20BlueA700: "font-gilroy font-medium",
  txtPoppinsRegular18: "font-normal font-poppins",
  txtGilroyMedium16Bluegray900: "font-gilroy font-medium",
  txtInterMedium16: "font-inter font-medium",
  txtGilroySemiBold16Green600: "font-gilroy font-semibold",
  txtGilroyRegular15Gray500: "font-gilroy font-normal",
  txtGilroySemiBold36: "font-gilroy font-semibold",
  txtGilroyMedium18Bluegray900: "font-gilroy font-medium",
  txtGilroySemiBold16Black900: "font-gilroy font-semibold",
  txtGilroyBold28Gray90002: "font-bold font-gilroy",
  txtGilroyMedium14Bluegray400: "font-gilroy font-medium",
  txtChivoBold50: "font-chivo font-normal",
  txtGilroySemiBold18BlueA700: "font-gilroy font-semibold",
  txtOpenSansMedium24: "font-medium font-opensans",
  txtGilroySemiBold16BlueA700: "font-gilroy font-semibold",
  txtOpenSansMedium20: "font-medium font-opensans",
  txtGilroyMedium24Green600: "font-gilroy font-medium",
  txtGilroyBold18: "font-bold font-gilroy",
  txtGilroyMedium16Black900: "font-gilroy font-medium",
  txtGilroyRegular18Bluegray500: "font-gilroy font-normal",
  txtGilroyMedium18Black900: "font-gilroy font-medium",
  txtGilroySemiBold16Red700: "font-gilroy font-semibold",
  txtGilroyMedium20: "font-gilroy font-medium",
  txtGilroyMedium20Bluegray400: "font-gilroy font-medium",
  txtGilroyMedium18Green600: "font-gilroy font-medium",
  txtGilroyMedium24: "font-gilroy font-medium",
  txtGilroySemiBold16Bluegray200: "font-gilroy font-semibold",
  txtGilroyMedium24Bluegray900: "font-gilroy font-medium",
  txtGilroySemiBold24Bluegray900: "font-gilroy font-semibold",
  txtGilroyMedium24Black90001: "font-gilroy font-medium",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtGilroyMedium14Gray800: "font-gilroy font-medium",
  txtGilroySemiBold24BlueA700: "font-gilroy font-semibold",
  txtOpenSansMedium24Bluegray900: "font-medium font-opensans",
  txtGilroyMedium16Bluegray400: "font-gilroy font-medium",
  txtGilroyRegular14Bluegray400: "font-gilroy font-normal",
  txtGilroyBold18Bluegray400: "font-bold font-gilroy",
  txtGilroyMedium16Bluegray40001: "font-gilroy font-medium",
  txtOpenSansMedium18Bluegray400: "font-medium font-opensans",
  txtOpenSansRomanSemiBold16: "font-opensans font-semibold",
  txtMontserratMedium14: "font-medium font-montserrat",
  txtGilroyRegular16Bluegray200: "font-gilroy font-normal",
  txtGilroyMedium14: "font-gilroy font-medium",
  txtGilroyMedium18BlueA700: "font-gilroy font-medium",
  txtGilroyMedium15: "font-gilroy font-medium",
  txtGilroyRegular12: "font-gilroy font-normal",
  txtGilroyMedium12: "font-gilroy font-medium",
  txtGilroySemiBold18: "font-gilroy font-semibold",
  txtGilroyMedium18: "font-gilroy font-medium",
  txtGilroyRegular12Bluegray40001: "font-gilroy font-normal",
  txtGilroyRegular15: "font-gilroy font-normal",
  txtGilroyRegular16: "font-gilroy font-normal",
  txtGilroySemiBold16: "font-gilroy font-semibold",
  txtGilroyMedium16: "font-gilroy font-medium",
  txtGilroySemiBold15: "font-gilroy font-semibold",
  txtGilroyRegular15Gray90003: "font-gilroy font-normal",
  txtOpenSansRomanSemiBold12: "font-opensans font-semibold",
  txtGilroyRegular14: "font-gilroy font-normal",
  txtGilroyBold24BlueA700: "font-bold font-gilroy",
  txtGilroyMedium18Bluegray600: "font-gilroy font-medium",
  txtGilroySemiBold16Bluegray700: "font-gilroy font-semibold",
  txtGilroySemiBold16Bluegray900: "font-gilroy font-semibold",
  txtGilroySemiBold18Gray90002: "font-gilroy font-semibold",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
